### ISSUE TITLE
Enter user details in db using google Oauth and ajax call

### ISSUE THREAD

**Issue by ashwani1218** [ashwani1218/OpenMEMEs#3]
When successfully logged in using the sign-in with google auth if in session redirect to the home page else add the user into the session.

**Comment by Fire-Hound** [comment]
Session part is remaining. Commits 57789f5ff38b0f29f6858ba2faf3d8dd0e80cb2c and 556ec695764049aed14ae87d18fad7c82ed83e0f solved the db part and google authentication.
